spring.application.name=pathpilot

spring.datasource.url=jdbc:postgresql://localhost:5432/pathpilot
spring.datasource.username=cyriltherichkid
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true